/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.firebears.javatest;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void multiplyNumbers() {
        float x = 4.6f;
        float y = 9.1f;

        // to store the multiplied value
        float result = x * y;

        // to print the product
        System.out.println("The product of " + x + " and " + y + " is: " + result);
    }

    public static void addNumber(){
        double num1 = 3.5;
        double num2 = 4.5;
        double thesum = num1 + num2;
        System.out.println("The sum of " + num1 + " and " + num2 + " is: " + thesum);
    }

    public static void main(String[] args) {
        // System.out.println(new App().getGreeting());
        addNumber();
    }
}
